// <auto-generated />
using System;
using Market.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Market.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Market.Entities.MarketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2f491f6-6789-4f28-b5aa-3fbbd9e3bfb4"),
                            CreatedAt = new DateTime(2025, 4, 13, 1, 22, 18, 866, DateTimeKind.Utc),
                            IsDeleted = false,
                            Location = "Hercegovina",
                            Name = "Market 1"
                        },
                        new
                        {
                            Id = new Guid("dddd8eaf-6d12-4d53-8315-902f50c65ae1"),
                            CreatedAt = new DateTime(2025, 4, 13, 1, 22, 18, 866, DateTimeKind.Utc),
                            IsDeleted = false,
                            Location = "Bosna",
                            Name = "Market 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
